import { Language } from './types';

export const TRANSLATIONS = {
  tr: {
    appTitle: 'Tournament Tracker',
    createTournament: 'Turnuva Oluştur',
    tournamentName: 'Turnuva Adı',
    type: 'Oyun Modu',
    awayGoals: 'Deplasman Golü Kuralı',
    rounds: 'Tur Sayısı',
    singleRound: 'Tek Maç',
    doubleRound: 'Rövanşlı (Home/Away)',
    players: 'Oyuncular',
    addPlayer: 'Oyuncu Ekle',
    startTournament: 'Fikstürü Oluştur ve Başla',
    fixtures: 'Fikstür',
    standings: 'Puan Durumu',
    stats: 'İstatistikler',
    match: 'Maç',
    round: 'Tur',
    vs: 'vs',
    enterScore: 'Skor Gir',
    selectTeam: 'Takım Seç',
    save: 'Kaydet',
    cancel: 'İptal',
    teamStats: 'Takım Performansları',
    playerName: 'Oyuncu Adı',
    p: 'O', // Played
    w: 'G', // Won
    d: 'B', // Drawn
    l: 'M', // Lost
    gf: 'A', // Goals For
    ga: 'Y', // Goals Against
    gd: 'AV', // Goal Diff
    pts: 'P', // Points
    mostWins: 'En Çok Kazanan Takımlar',
    noMatches: 'Henüz maç oynanmadı.',
    enterName: 'Adını yaz...',
    remove: 'Sil',
    playerCountError: 'En az 2 oyuncu gereklidir (2v2 için en az 4).',
    settings: 'Ayarlar',
    theme: 'Tema',
    language: 'Dil',
    completed: 'Tamamlandı',
    upcoming: 'Oynanacak',
    reset: 'Turnuvayı Sil',
    resetConfirm: 'Bu turnuva kalıcı olarak silinecek. Emin misiniz?',
    teamSelection: 'Futbol Takımı (Örn: Galatasaray)',
    scoreInput: 'Skor',
    home: 'Ev Sahibi',
    away: 'Deplasman',
    winner: 'Kazanan',
    draw: 'Beraberlik',
    dashboard: 'Turnuva Paneli',
    activeTournaments: 'Aktif Turnuvalar',
    history: 'Geçmiş',
    noActiveTournaments: 'Aktif turnuva bulunmuyor.',
    noArchivedTournaments: 'Geçmiş turnuva bulunmuyor.',
    resume: 'Devam Et',
    view: 'İncele',
    backToDashboard: 'Panele Dön',
    finishTournament: 'Turnuvayı Tamamla',
    finishConfirm: 'Bu turnuvayı tamamlayıp geçmişe taşımak istiyor musunuz?',
    status: 'Durum',
    date: 'Tarih',
    newTournament: 'Yeni Turnuva',
    ghostMatch: 'Bu takım için puan hesaplanmaz (Dengeleyici Maç)',
    recommended: 'Önerilen',
    matches: 'Maçlar',
    progress: 'İlerleme', // İlerleme (Progress)
    leader: 'Lider',
    goals: 'Goller',
    loading: 'Yükleniyor...',
    account: 'Hesap',
    deleteAccount: 'Hesabı Sil',
    deleteAccountDesc: 'Hesabınızı ve tüm turnuva verilerinizi kalıcı olarak silin. Bu işlem geri alınamaz.',
    deleteAccountConfirm: 'Hesabınızı silmek istediğinizden emin misiniz? Bu işlem TÜM verilerinizi kalıcı olarak silecektir.',
    deleteAccountFailure: 'Hesap silinemedi. Önce çıkış yapıp tekrar giriş yapmanız gerekebilir.',
    verifyEmail: 'E-postanızı Doğrulayın',
    verifyEmailDesc: 'Turnuva oluşturmak için lütfen e-posta adresinizi doğrulayın.',
    resendEmail: 'Doğrulama E-postası Gönder',
    verificationSent: 'Doğrulama e-postası gönderildi!',
    dailyLimit: 'Günlük turnuva limiti aşıldı (maksimum 5).',
    loginError: 'Kimlik doğrulama başarısız. Lütfen bilgilerinizi kontrol edin.',
    loginLimit: 'Günlük giriş limiti aşıldı (maksimum 10).',
    winRate: 'Kazanma Oranı'
  },
  en: {
    appTitle: 'Tournament Tracker',
    createTournament: 'Create Tournament',
    tournamentName: 'Tournament Name',
    type: 'Game Mode',
    awayGoals: 'Away Goals Rule',
    rounds: 'Rounds',
    singleRound: 'Single Leg',
    doubleRound: 'Double Leg (Home/Away)',
    players: 'Players',
    addPlayer: 'Add Player',
    startTournament: 'Generate Fixtures & Start',
    fixtures: 'Fixtures',
    standings: 'Standings',
    stats: 'Statistics',
    match: 'Match',
    round: 'Round',
    vs: 'vs',
    enterScore: 'Enter Score',
    selectTeam: 'Select Team',
    save: 'Save',
    cancel: 'Cancel',
    teamStats: 'Team Performances',
    playerName: 'Player Name',
    p: 'P',
    w: 'W',
    d: 'D',
    l: 'L',
    gf: 'GF',
    ga: 'GA',
    gd: 'GD',
    pts: 'Pts',
    mostWins: 'Most Winning Teams',
    noMatches: 'No matches played yet.',
    enterName: 'Enter name...',
    remove: 'Remove',
    playerCountError: 'Minimum 2 players required (4 for 2v2).',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    completed: 'Completed',
    upcoming: 'Upcoming',
    reset: 'Delete Tournament',
    resetConfirm: 'This tournament will be permanently deleted. Are you sure?',
    teamSelection: 'Football Club (e.g. Man City)',
    scoreInput: 'Score',
    home: 'Home',
    away: 'Away',
    winner: 'Winner',
    draw: 'Draw',
    dashboard: 'Dashboard',
    activeTournaments: 'Active Tournaments',
    history: 'History',
    noActiveTournaments: 'No active tournaments.',
    noArchivedTournaments: 'No archived tournaments.',
    resume: 'Resume',
    view: 'View',
    backToDashboard: 'Back to Dashboard',
    finishTournament: 'Finish Tournament',
    finishConfirm: 'Do you want to complete this tournament and move it to history?',
    status: 'Status',
    date: 'Date',
    newTournament: 'New Tournament',
    ghostMatch: 'No points calculated for this team (Balancing Match)',
    recommended: 'Recommended',
    matches: 'Matches',
    progress: 'Progress',
    leader: 'Leader',
    goals: 'Goals',
    loading: 'Loading...',
    account: 'Account',
    deleteAccount: 'Delete Account',
    deleteAccountDesc: 'Permanently delete your account and all tournament data. This action cannot be undone.',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This will erase ALL your data permanently.',
    deleteAccountFailure: 'Failed to delete account. You may need to re-login first.',
    verifyEmail: 'Verify Email',
    verifyEmailDesc: 'Please verify your email address to create tournaments.',
    resendEmail: 'Resend Email',
    verificationSent: 'Verification email sent!',
    dailyLimit: 'Daily tournament limit exceeded (max 5).',
    loginError: 'Authentication failed. Please check your credentials.',
    loginLimit: 'Daily login limit exceeded (max 10).',
    winRate: 'Win Rate'
  }
};

export const POPULAR_TEAMS = [
  "Real Madrid", "Barcelona", "Man City", "Liverpool", "Arsenal", 
  "Bayern Munich", "PSG", "Inter", "Milan", "Juventus", 
  "Galatasaray", "Fenerbahçe", "Beşiktaş", "Trabzonspor"
];